### ISSUE TITLE
Revert bot state. Bring back simulate move

### ISSUE THREAD

**Issue by Debilski** [ASPP/pelita#844]
We currently prepare the bot state in `game.py` in a scheme that mirrors the way it is later used by the `Bot` API.

```yaml
game_state:
    team: 
        team_index: 1
        bot_positions: [[29,1],[30,2]]
        score: 0
        kills: [0,0]
        deaths: [0,0]
        bot_was_killed: [false,false]
        error_count: 0
        food: [[...]]
        name: Smart Random Players
        team_time: 0.001439541985746473
    enemy: 
        team_index: 0
        bot_positions: [[1,8],[1,13]]
        is_noisy: [true,true]
        score: 0
        kills: [0,0]
        deaths: [0,0]
        bot_was_killed: [false,false]
        error_count: 0
        food: [[...]]
        shaded_food: []
        name: Smart Eating Players
        team_time: 0.006159459124319255
    round: 2
    bot_turn: 1
    timeout_length: 3
    max_rounds: 300
```

There is some sense to this as it leaves out unnecessary information. For example, we do not need to send `is_noisy` information for our own bot.

This comes with a disadvantage, however, in that more advanced code that might want to use a different API has to revert these decisions. Specifically, code that wants to re-use the `apply_move` function to simulate a move has to reimplement the logic of `apply_move` targeted at the `Bot` API or write a conversion function from `Bot` API back to `game_state` (and fear that this breaks whenever new properties are added).

My proposal would be to create the `Bot` API on the client side and instead send a data structure similar to the game state (properly cleaned up from unnecessary/confidential data). A normal user would not see any difference when using the `Bot` API but a power user could still access the original game state behind a attribute.

Reference to a prior implementation of `simulate_move`: https://github.com/ASPP/pelita/pull/399
